### ISSUE TITLE
Episode not found

### ISSUE THREAD

**Issue by Nindohana** [the-lazy-fox/script.tvtime#7]
Hello !
Thank you for your fork of this project.
On the original script and with yours i'm getting "Episode not found" everytime i'm playing something.
The weird thing is that when I force sync Kodi>TVTime, it works perfectly.
I don't know if this can be a problem but i'm using PlexKodiConnect Add-on on Kodi to link it with my Plex database.
Also I'm French so all the title/resume of my episodes are in French.
Also I'm on a Nvidia Shield TV.

Maybe I should link you with the logs ?

I've seen this issue in the #3 but this guy deleted a part of your code that I can't find so I guess you modified it yourself ?

Thanks in advance,

**Comment by Nindohana** [comment]
@alxlaxv Do you have any idea what could be the issue ?
Are you still active on this project ?

**Comment by the-lazy-fox** [comment]
Hi! 
I’m not really active on this. I have made this fork to be able to merge and build a release if some members know how to fix the issues.
Feel free to submit code changes if you are comfortable with it.

**Comment by Nindohana** [comment]
@alxlaxv Thank you for your answer. I'm not comfortable enough with coding to know what to change unfortunately.
For anyone else stopping by, I managed to make the add-on work but now it gets the wrong show everytime.

**Comment by JosemyAB** [comment]
I had same error with Kodi (18.3). Im using The Movie Database as scrapper because is default in this Kodi version due TV Database Scrapper has changed the API and not works well.

The problem was the plugin searchs the episode in TVTime using the TMDB episode_id. I guess TVTime use TVDB episode id.

I have change the code to search by file name instead episode_id. It works well with my version (Kodi (18.3) over OSMC)

I have create a merge request for create a new version if needed: https://github.com/alxlaxv/script.tvtime/pull/8

Meanwhile you can overwrite  file "default.py" in "/home/osmc/.kodi/addons/script.tvtime" folder with my version. After restart, should works OK.

**Comment by Nindohana** [comment]
Thank you, it works perfectly with your fork and after a reboot.

**Comment by the-lazy-fox** [comment]
Thanks for your PR.
I will check this and build a version as soon as possible.

**Comment by the-lazy-fox** [comment]
Release published! Thanks!
https://github.com/alxlaxv/script.tvtime/releases/tag/1.2.4
